apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sankar
  name: second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sankar
  strategy: {}
  template:
    metadata:
      labels:
        app: sankar
    spec:
      containers:
      - image: nginx
        name: nginx
