name: My second workflow
on: push
jobs: 
    first_job:
             runs-on: ubuntu-latest
             steps:
             - name: Welcome Message
               run: echo "This Is My second Message"
             - name: listing all files
                run: ls
                            
