name: My second workflow
on: push
jobs: 
    first_job:
             runs-on: ubuntu-latest
             steps:
             - name: checkout the repo
               uses: actions/checkout@v7
             - name: Welcome Message
               run: | 
                echo "This Is My second Message"
                ls
                pwd
            